controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (James_Duck.vy == 0) {
        James_Duck.vy += -220
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.gameOver(true)
    music.play(music.melodyPlayable(music.magicWand), music.PlaybackMode.UntilDone)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.rock2, function (sprite, location) {
    game.gameOver(false)
})
let James_Duck: Sprite = null
scene.setBackgroundColor(6)
James_Duck = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ............fffff.......
    ...........f55555f......
    ..........f5555555f.....
    ..........ff5f1f5f1f....
    ..........f5f1fff1ff....
    ..........f55fff4fff....
    ........fff55555445f....
    .......f5555555555f.....
    ......f555555555555f....
    ....ff55ff5555555555f...
    ...f555555ff55555555f...
    ...f5555555555555555f...
    ....f55555555555555f....
    .....f555555555555f.....
    ......ffff555555f.......
    ..........ffffff........
    ..........ff..ff........
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(James_Duck, 100, 0)
tiles.setCurrentTilemap(tilemap`Level 1`)
James_Duck.ay = 350
scene.cameraFollowSprite(James_Duck)
James_Duck.setPosition(26, 28)
